#include <myl/version.hpp>

#include <catch2/catch_all.hpp>

#define TEST_VERSION_MAJOR 1
#define TEST_VERSION_MINOR 2
#define TEST_VERSION_PATCH 3
#define TEST_VERSION MYL_MAKE_VERSION(TEST_VERSION_MAJOR, TEST_VERSION_MINOR, TEST_VERSION_PATCH)
#define TEST_VERSION_STRING MYL_MAKE_VERSION_STRING(TEST_VERSION_MAJOR, TEST_VERSION_MINOR, TEST_VERSION_PATCH)

TEST_CASE("version macros", "[version.hpp]") {
	CHECK(MYL_VERSION_EXTRACT_MAJOR(TEST_VERSION) == 1);
	CHECK(MYL_VERSION_EXTRACT_MINOR(TEST_VERSION) == 2);
	CHECK(MYL_VERSION_EXTRACT_PATCH(TEST_VERSION) == 3);
	CHECK(TEST_VERSION == 0b00000001'00000010'00000000'00000011);
	CHECK(TEST_VERSION_STRING == "1.2.3");
}
