# Setup CL and Link for C and C++

set(CMAKE_C_COMPILER "cl")
set(CMAKE_C_FLAGS "/Wall /std:c${CMAKE_C_STANDARD}")
set(CMAKE_C_FLAGS_RELEASE        "/O2 /DNDEBUG")
set(CMAKE_C_FLAGS_RELWITHDEBINFO "/O2 /Zo /DDEBUG")
set(CMAKE_C_FLAGS_DEBUG          "/Od /Zi /DDEBUG")
set(CMAKE_C_FLAGS_MINSIZEREL     "/O1 /DNDEBUG")

set(CMAKE_CXX_COMPILER "cl")
set(CMAKE_CXX_FLAGS "/Wall /std:c++${CMAKE_CXX_STANDARD}")
set(CMAKE_CXX_FLAGS_RELEASE        "/O2 /DNDEBUG")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "/O2 /Zo /DDEBUG")
set(CMAKE_CXX_FLAGS_DEBUG          "/Od /Zi /DDEBUG")
set(CMAKE_CXX_FLAGS_MINSIZEREL     "/O1 /DNDEBUG")

set(CMAKE_LINKER "link")