# Setup Clang-CL and LLD for C and C++

set(CMAKE_C_COMPILER "clang-cl")
set(CMAKE_C_FLAGS "/W4 /std:c${CMAKE_C_STANDARD}")
set(CMAKE_C_FLAGS_RELEASE        "/O2 /DNDEBUG")
set(CMAKE_C_FLAGS_RELWITHDEBINFO "/O2 /Zo /DDEBUG")
set(CMAKE_C_FLAGS_DEBUG          "/Od /Zi /DDEBUG")
set(CMAKE_C_FLAGS_MINSIZEREL     "/O1 /DNDEBUG")

set(CMAKE_CXX_COMPILER "clang-cl")
set(CMAKE_CXX_FLAGS "/W4 /std:c++${CMAKE_CXX_STANDARD}")
set(CMAKE_CXX_FLAGS_RELEASE        "/O2 /DNDEBUG")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "/O2 /Zo /DDEBUG")
set(CMAKE_CXX_FLAGS_DEBUG          "/Od /Zi /DDEBUG")
set(CMAKE_CXX_FLAGS_MINSIZEREL     "/O1 /DNDEBUG")

set(CMAKE_LINKER "lld-link")